---
title: "eda2"
author: "Adam Chandler"
date: "3/1/2018"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }

# Load libraries

library(tidyverse)
library(tidytext)
library(knitr)
library(stringr)
library(kableExtra)


# Load data
ld_survey <- read_csv("data/ld_survey_anonymized_20180301.csv")
names(ld_survey) <- c("response_id", "ld_features", "rev1_score", "rev2_score", "rev3_score", "rev4_score", "features_total_score")

```


# Highest features score

```{r}

ld_survey %>%
  top_n(1, wt = features_total_score) %>%
  kable("html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```

# Lowest features total scores


```{r}

ld_survey %>%
  top_n(-1, wt = features_total_score) %>%
  kable("html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```


```{r}

summary(ld_survey$features_total_score)

ggplot(ld_survey, aes(features_total_score)) + geom_histogram(binwidth = 1) +
  ggtitle("\nLD Survey features total scores distribution", subtitle = "D4D")

```

