---
title: "eda3"
author: "Adam Chandler"
date: "3/1/2018"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }

# Load libraries

library(tidyverse)
library(tidytext)
library(knitr)
library(stringr)
library(kableExtra)
data("stop_words")
library(wordcloud)


# Load data
ld_survey <- read_csv("data/ld_survey_anonymized_20180301.csv")
names(ld_survey) <- c("response_id", "ld_features", "rev1_score", "rev2_score", "rev3_score", "rev4_score", "features_total_score")

```


# Remove responses with 0 feature total score

```{r}

ld_survey_nonzero <- ld_survey %>%
  filter(features_total_score > 0)

```

# Review words in non-zero feature responses

```{r}

tidy_words <- ld_survey_nonzero %>% 
  unnest_tokens(word, ld_features) %>%
  count(word, sort = TRUE)


```

# Remove stop words

```{r}

tidy_words <- ld_survey_nonzero %>% 
  unnest_tokens(word, ld_features) %>%
  count(word, sort = TRUE)

tidy_words_stopped <- tidy_words %>%
  anti_join(stop_words)

```


# Let's go back a step and clean up the data a little by normalizing permutations of "linked data" then take a look

```{r}
ld_survey_cleaned <- ld_survey_nonzero
ld_survey_cleaned$ld_features <- str_replace_all(ld_survey_cleaned$ld_features, "linked data", "linked_data")
ld_survey_cleaned$ld_features <- str_replace_all(ld_survey_cleaned$ld_features, "linked open data", "linked_data")
ld_survey_cleaned$ld_features <- str_replace_all(ld_survey_cleaned$ld_features, "lod", "linked_data")


tidy_words_stopped <- ld_survey_cleaned %>% 
  unnest_tokens(word, ld_features) %>%
  count(word, sort = TRUE) %>%
  anti_join(stop_words) 


```

# Wordcloud (a bit unpredictable)

```{r}

tidy_words_stopped %>%
  with(wordcloud(word, n, max.words = 50))

```


```{r}

tidy_words_tf <- ld_survey_cleaned %>% 
  unnest_tokens(word, ld_features) %>%
  count(response_id, word, sort = TRUE) %>%
  anti_join(stop_words) %>%
  ungroup()

total_words <- tidy_words_tf %>%
  group_by(response_id) %>%
  summarize(total = sum(n))

tidy_words_tf <- left_join(tidy_words_tf, total_words)

freq_by_rank <- tidy_words_tf %>%
  group_by(response_id) %>%
  mutate(rank = row_number(), term_frequency = n/total)

words_tf_idf <- tidy_words_tf %>%
  bind_tf_idf(word, response_id, n)

```





